spring:
  kafka:
    consumer:
      client-id: "kafka-voice-command-consumer"
      group-id: "kafka-voice-command-consumer"

    bootstrap-servers:
      - localhost:29092
    properties:
      # cache.max.bytes.buffering: 0
      auto.offset.reset: earliest
    streams:
      application-id: kafka-voice-command-processor
      properties:
        num.stream.threads: ${messaging.concurrency}

messaging:
  concurrency: 5
